### ISSUE TITLE
persistent subscription ack failure when writing many events on same connection 

### ISSUE THREAD

**Issue by dvic** [NFIBrokerage/spear#87]
We've encountered an issue where persistent subscriptions would experience slowdowns because it seems like acknowledgments are not being processed (message would be retried). We've been able to reproduce it in [1]. The fix for us has been to use a separate connection for writing and for connecting to the persistent subscription. Not sure if this is expected behaviour (or an appropriate fix). Is this something that's a known issue?

[1] script demonstrating issue: https://gist.github.com/dvic/a2177efd0d95fc6ff755b2650928cbca (setting `separate_clients = true`) fixes the issue

**Comment by the-mikedavis** [comment]
I pushed up a change in https://github.com/NFIBrokerage/spear/commit/f34baac2ee3c8a848f0c78b9f4e39502ca8d1e19 that resolves this for me locally. I'll test it out a bit more and if it all looks good I'll make a release soon

**Comment by the-mikedavis** [comment]
Ok f34baac is now released in v1.3.1. Thanks again for the reproduction case and report!
